name: Security Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "garadyusuf/hello-world-app:latest"
          format: "table"
          exit-code: 1
          severity: "HIGH,CRITICAL"
    

      - name: Send AWS SNS Alert on Failure
        if: failure()
        run: |
          aws sns publish \
            --region ${{ secrets.AWS_REGION }} \
            --topic-arn ${{ secrets.SNS_TOPIC_ARN }} \
            --message "Security scan failed for Docker image garadyusuf/hello-world-app:latest in repository $GITHUB_REPOSITORY. Check the workflow run for details."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
